name: pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - seroba=1.0.2
  - fastp=0.23.2
  - quast=5.2.0
  - ariba=2.14.6
  - bcftools=1.12
  - biopython=1.77
  - kmc=3.1.0
  - tbb=2021.7.0
  - mummer=3.23=*_11 # MacOS needs to use build-specific mummer 3.23, as the default build causes fatal error
  - nextflow=22.10
  - git=2.38.1
  - jq=1.6
  - bc=1.07.1
  - kraken2=2.1.2
  # MacOS specific packages below
  - blast=2.12.0