name: pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - seroba=1.0.2
  - fastp=0.23.2
  - quast=5.2.0
  - ariba=2.14.6
  - bcftools=1.12
  - biopython=1.77
  - kmc=3.1.0
  - tbb=2021.7.0
  - mummer=3.23
  - nextflow>=22.10
  - git
  - pandas=1.3.5
  # Linux specific packages below
  - unicycler=0.5.0
  - spades=3.15.5