name: pipeline
channels:
  - bioconda
  - conda-forge
  - etetoolkit # Bioconda channel only has t_coffee package for Linux
  - defaults
  - r
dependencies:
  - quast=5.2.0
  - bcftools=1.12
  - nextflow=22.10
  - bc=1.07.1
  - bwa=0.7.17
  - samtools=1.12
  - shovill=1.1.0
  # MacOS specific packages below
  - blast=2.12.0